repos:
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: python -m pytest
      language: system
      pass_filenames: false
      always_run: true
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
